import { Inter } from "next/font/google";
import "./globals.css";
import AOSProvider from "./providers"; // client component

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Portfolio: Somenath Paul",
  description: "Generated by create next app",
  icons: {
    icon: "/tab-logo.png", // Path inside /public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AOSProvider>
          {children}
        </AOSProvider>
      </body>
    </html>
  );
}
